### PR TITLE
#11 When summary has non numeric "pct", the output is "Unknown%" 

### PR DESCRIPTION
**Pull request by michaelrodov**
- fixed not numeric pct (percentage) to be 0

### CODE REVIEW

**Review by pamepeixinho — APPROVED** [review]

**Comment by michaelrodov** [comment]
Hi Pam
can you please publish the new version?
thanks

**Comment by michaelrodov** [comment]
hey pamela
can you give me permission to publish the package on npm after you approve
merge requests
?
thanks

**Comment by michaelrodov** [comment]
Pamela can you please publish a new version? thanks

**Comment by michaelrodov** [comment]
Hi can you please publish the new version 1.3

**Comment by michaelrodov** [comment]
Pamela, can you please publish a new version?

**Pull request merged**
